services:
  airflow-standalone:
    image: airflow-standalone
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
    volumes:
      - ./airflow/dags:/workspace/airflow/dags
      - ./airflow/secret:/workspace/airflow/secret
      - ./datalake:/workspace/datalake
      - ./src:/workspace/src
    ports:
      - 8080:8080

  database:
    image: postgres:bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
